name: Quality Checks
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: "Quality Checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Dependencies
        run: nix-shell --command "pnpm install --frozen-lockfile"

      - name: Lint / TSC / Test
        run: nix-shell --command "turbo build"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '.github/tests/*.xml'

#      - uses: andresz1/size-limit-action@v1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: |
            .github/tests/*.xml
        if: always()
